 export const announcements = [
    {
      id: 1,
      title: "Emergency: Campus Closure Due to Weather",
      content:
        "Due to severe weather conditions, the campus will be closed today. All classes will be conducted online. Please check your course portals for virtual meeting links.",
      type: "school",
      priority: "urgent",
      author: "Emergency Management Office",
      date: "2024-03-15",
      time: "06:00 AM",
      course: null,
      isRead: false,
      isPinned: true,
      category: "Emergency",
      tags: ["urgent", "weather", "closure", "online"],
      reactions: { likes: 45, comments: 12 },
      attachments: ["weather-update.pdf"],
    },
    {
      id: 2,
      title: "Final Exam Schedule Released - Spring 2024",
      content:
        "The final examination schedule for Spring 2024 semester is now available. Please review your exam dates and locations carefully. Contact your instructors for any conflicts.",
      type: "school",
      priority: "high",
      author: "Academic Affairs Office",
      date: "2024-03-14",
      time: "10:30 AM",
      course: null,
      isRead: false,
      isPinned: true,
      category: "Academic",
      tags: ["finals", "schedule", "important"],
      reactions: { likes: 128, comments: 34 },
      attachments: ["final-exam-schedule.pdf"],
    },
    {
      id: 3,
      title: "Database Systems - Project Deadline Extended",
      content:
        "Due to server maintenance issues last week, the final project deadline for Database Systems has been extended to March 25th. Updated rubric and submission guidelines are available.",
      type: "course",
      priority: "high",
      author: "Prof. Michael Chen",
      date: "2024-03-13",
      time: "02:15 PM",
      course: "CS 301 - Database Systems",
      isRead: true,
      isPinned: false,
      category: "Assignment",
      tags: ["extension", "project", "deadline"],
      reactions: { likes: 67, comments: 8 },
      attachments: ["updated-rubric.pdf"],
    },
    {
      id: 4,
      title: "New Student Success Center Opening",
      content:
        "We're excited to announce the opening of our new Student Success Center in Building A, Room 150. Services include tutoring, academic coaching, and career counseling.",
      type: "school",
      priority: "medium",
      author: "Student Services",
      date: "2024-03-12",
      time: "11:45 AM",
      course: null,
      isRead: true,
      isPinned: false,
      category: "Services",
      tags: ["new", "tutoring", "support"],
      reactions: { likes: 89, comments: 15 },
      attachments: [],
    },
    {
      id: 5,
      title: "Object Oriented Programming - Guest Speaker Event",
      content:
        "Join us for an exclusive talk by Sarah Johnson, Senior Software Engineer at Google, on 'Modern Design Patterns in Large-Scale Applications' this Friday at 2:00 PM.",
      type: "course",
      priority: "medium",
      author: "Dr. Emily Rodriguez",
      date: "2024-03-11",
      time: "04:20 PM",
      course: "CS 201 - Object Oriented Programming",
      isRead: false,
      isPinned: true,
      category: "Event",
      tags: ["guest speaker", "industry", "design patterns"],
      reactions: { likes: 156, comments: 23 },
      attachments: ["speaker-bio.pdf"],
    },
    {
      id: 6,
      title: "Library Extended Hours During Finals Week",
      content:
        "The library will be open 24/7 during finals week (March 18-22). Additional study spaces and computer labs will also be available. Quiet zones will be strictly enforced.",
      type: "school",
      priority: "medium",
      author: "Library Services",
      date: "2024-03-10",
      time: "09:30 AM",
      course: null,
      isRead: true,
      isPinned: false,
      category: "Services",
      tags: ["library", "finals", "extended hours"],
      reactions: { likes: 203, comments: 41 },
      attachments: [],
    },
  ]

  export const trendingTopics = [
    { name: "Final Exams", mentions: 45, trend: "up" },
    { name: "Weather Closure", mentions: 38, trend: "up" },
    { name: "Project Extensions", mentions: 22, trend: "stable" },
    { name: "Guest Speakers", mentions: 18, trend: "up" },
    { name: "Library Hours", mentions: 15, trend: "down" },
  ]

  export const recentActivity = [
    { action: "New announcement", item: "Campus Closure", time: "2 min ago" },
    { action: "Updated", item: "Exam Schedule", time: "1 hour ago" },
    { action: "Comment added", item: "Project Extension", time: "3 hours ago" },
    { action: "New announcement", item: "Success Center", time: "1 day ago" },
  ]
